Feat: added game, fix of non compile and basic matchmaking
rubenoid/ft_transcendence pull request #33
Opened 2022-01-04 20:07 UTC by Alpha1337k

2022-01-05 12:36 UTC, harou24 requested changes
Not working yet, once it works we'll merge

2022-01-05 13:59 UTC, Alpha1337k commented
done!

2022-01-05 18:31 UTC, harou24 requested changes
Errors while running

2022-01-06 12:35 UTC, harou24 approved these changes
Good !

2022-01-06 12:36 UTC, merged